### ISSUE TITLE
Help using newman scripts

### ISSUE THREAD

**Issue by afrancoc2000** [pacroy/abap-ci-postman#1]
Hi @pacroy 

I was reading your article about implementing a [CI pipeline for SAP](https://medium.com/pacroy/continuous-integration-in-abap-3db48fc21028) and I really liked it so, I started Implementing my own but I'm having a little trouble in the implementation.

I have been trying to use the scripts in my system but every time I run them I get a timeout, the thing is that I have SAP Development Tools instaled and I can run tests from Eclipse without problem, I thought my problem is the port I'm using so I traced my requests using the Resource Monitor and I got that my requests are being generated from <<myHost>>:3300 port.

Also when I run SAP Gui the system tells me that the requests come from <<myHost>>:3200.

I tried both this ports with no success and no good error, I also tried the port that came configured in the NPL file (8000) but that didn't work either.

Do you have like a guide for using this REST API? I'm a little lost I would like to test the most simple one to see if I can get a connection I tried http(s)://<your host and port>/sap/bc/adt/discovery with both ports with no success so is there something I'm missing? somewhere to look? a guide to follow?

Thank you very much

**Comment by afrancoc2000** [comment]
Sorry, found my problem was SSL, finally port 8443 makes the trick :D now I need authorization.

Thanks!!!

**Comment by himanshush13** [comment]
Hello @afrancoc2000 ,
we are also following the same, but we are getting issues, as jenkins couldn't read the json files with groovy and without groovy.
Any hint or help from your side will be appreciated.
